/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionRouteImport } from './routes/session'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MarketIntelRouteImport } from './routes/market-intel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FloatingRouteImport } from './routes/floating'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiAceChatRouteImport } from './routes/api/ace-chat'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminAceRouteImport } from './routes/admin.ace'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIntelRoute = MarketIntelRouteImport.update({
  id: '/market-intel',
  path: '/market-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FloatingRoute = FloatingRouteImport.update({
  id: '/floating',
  path: '/floating',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAceChatRoute = ApiAceChatRouteImport.update({
  id: '/api/ace-chat',
  path: '/api/ace-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAceRoute = AdminAceRouteImport.update({
  id: '/ace',
  path: '/ace',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/floating': typeof FloatingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/market-intel': typeof MarketIntelRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ace': typeof AdminAceRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ace-chat': typeof ApiAceChatRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/floating': typeof FloatingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/market-intel': typeof MarketIntelRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ace': typeof AdminAceRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ace-chat': typeof ApiAceChatRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/floating': typeof FloatingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/market-intel': typeof MarketIntelRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ace': typeof AdminAceRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ace-chat': typeof ApiAceChatRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/download'
    | '/floating'
    | '/forgot-password'
    | '/journal'
    | '/login'
    | '/market-intel'
    | '/onboarding'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/session'
    | '/settings'
    | '/signals'
    | '/sitemap.xml'
    | '/admin/ace'
    | '/admin/activity'
    | '/admin/feedback'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/api/ace-chat'
    | '/admin/'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/download'
    | '/floating'
    | '/forgot-password'
    | '/journal'
    | '/login'
    | '/market-intel'
    | '/onboarding'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/session'
    | '/settings'
    | '/signals'
    | '/sitemap.xml'
    | '/admin/ace'
    | '/admin/activity'
    | '/admin/feedback'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/api/ace-chat'
    | '/admin'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/download'
    | '/floating'
    | '/forgot-password'
    | '/journal'
    | '/login'
    | '/market-intel'
    | '/onboarding'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/session'
    | '/settings'
    | '/signals'
    | '/sitemap.xml'
    | '/admin/ace'
    | '/admin/activity'
    | '/admin/feedback'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/api/ace-chat'
    | '/admin/'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DownloadRoute: typeof DownloadRoute
  FloatingRoute: typeof FloatingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  MarketIntelRoute: typeof MarketIntelRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SessionRoute: typeof SessionRoute
  SettingsRoute: typeof SettingsRoute
  SignalsRoute: typeof SignalsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAceChatRoute: typeof ApiAceChatRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-intel': {
      id: '/market-intel'
      path: '/market-intel'
      fullPath: '/market-intel'
      preLoaderRoute: typeof MarketIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floating': {
      id: '/floating'
      path: '/floating'
      fullPath: '/floating'
      preLoaderRoute: typeof FloatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/ace-chat': {
      id: '/api/ace-chat'
      path: '/api/ace-chat'
      fullPath: '/api/ace-chat'
      preLoaderRoute: typeof ApiAceChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ace': {
      id: '/admin/ace'
      path: '/ace'
      fullPath: '/admin/ace'
      preLoaderRoute: typeof AdminAceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAceRoute: typeof AdminAceRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAceRoute: AdminAceRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DownloadRoute: DownloadRoute,
  FloatingRoute: FloatingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  MarketIntelRoute: MarketIntelRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SessionRoute: SessionRoute,
  SettingsRoute: SettingsRoute,
  SignalsRoute: SignalsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAceChatRoute: ApiAceChatRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
